server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://Juandar047@bitbucket.org/codejuandar/dinnyms.git
          search-paths: config-data
  application:
    name: config-service
